# Generated by Django 3.0.1 on 2020-02-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='description',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='email',
            field=models.EmailField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
