# Generated by Django 3.0.1 on 2020-02-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200215_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='description',
            field=models.TextField(verbose_name=500),
        ),
    ]
